### ISSUE TITLE
Soulstruct does not show a context menu upon right clicking in the Goods or Weapons categories

### ISSUE THREAD

**Issue by YuiKitamura** [Grimrukh/soulstruct#11]
This means that there is no way to duplicate or create a new entry in these categories, so I cannot make my own weapons or items.

I have already tried reinstalling soulstruct after deleting its config, and restarting my PC. This problem did not start happening suddenly, as I have never been able to get a context menu in these categories.

**Comment by YuiKitamura** [comment]
Hey sorry I moved across the country. I've recently installed Soulstruct 1.2.3 and can confirm I have the same issue. I tried resetting my PC, reinstalling ptde entirely with a new mod folder and still encountered the same issue.

I recently purchased a laptop and installed ptde on there and again encountered the same issue on a completely different machine which just blows my mind.

My only guess is it would have something to do with explorer. I have open-shell installed on both computers, uninstalling the program on my main desktop did not fix the issue.

Honestly, if there was a keyboard shortcut I could use to just duplicate items/create a new entry in the list I would just use that and work around it.

**Comment by LukeLavan** [comment]
Stupid question, but your right click functions normally otherwise, right? You specifically mentioned the Goods and Weapons param categories, but does this work for other param categories? What about other tabs? Other programs entirely?

[This line](https://github.com/Grimrukh/soulstruct/blob/6c42ccc7191e22985bd94c679e6824742af85179/soulstruct/base/project/editors/base_editor.py#L339) is responsible for binding the `self._right_click_entry` function to `<Button-3>'. Is it possible your right click isn't mapped to button 3? Try right clicking on the button [here](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/button#result). You could try changing which button is bound here and see if that works.

Then, [this line](https://github.com/Grimrukh/soulstruct/blob/6c42ccc7191e22985bd94c679e6824742af85179/soulstruct/base/project/editors/base_editor.py#L803) renders (or is supposed to anyway) the context menu via `tk_popup` which comes directly from tkinter. How Python-savvy are you - could you run soulstruct through a debugger and add a breakpoint on this line? Alternatively you could add an arbitrary print statement before this line and look for what you print in the console. If this is beyond your capability don't sweat it, but I'm curious to know if we're at least reaching this part of the code or if the problem lies elsewhere.

Other dumb questions: are you launching soulstruct through the exe or as a python module? Could you try using a different mouse? What OS is your PC/laptop running?

**Comment by YuiKitamura** [comment]
Yes, my right click functions normally otherwise. This is the only program I've noticed with a problem like this.

Params - Weapons, Goods, Weapon Upgrades
Lighting - Tone Correction, Tone Mapping

I just checked every category and these are the ones I cannot right click in - or more specifically, I cannot produce a context menu in Soulstruct but I can still right click on anything else on my desktop just fine.

My right click is bound to button 3, I can right click anything on this page in github with no issues.

Sorry to say I'm a complete novice with Python. If you had a guide to do what you wanted me to I could follow though.

I'm launching Soulstruct as en exe. I used my trackpad on the laptop with the same issue so the mouse isn't the issue. Both my desktop and laptop are running the latest version of Windows 10.

**Comment by LukeLavan** [comment]
That's pretty strange, I can't see any reason why those five categories are different than the others. @Grimrukh any ideas?

**Comment by YuiKitamura** [comment]
I just wiped my entire SSD and installed Windows 11. I downloaded Firefox, Steam and then Soulstruct/DSfix/UnpackDSforModding.

I made a new project folder too.

I still cannot get a context menu on the same exact categories.

I just cannot imagine this being something on my end but apparently nobody else has the same problem. So I guess I give up.

**Comment by treacherousfiend** [comment]
Can confirm the exact same issue on the same 5 categories.
The one thing I can think of is that its due to me modding PTDE instead of DSR, but I can't test that theory.

**Comment by LukeLavan** [comment]
Interesting - as far as I can tell, none of the right click behavior should be any different based on which game is loaded. I wish I had PTDE so I could test this.

**Comment by YuiKitamura** [comment]
I've just confirmed that I can right click on all 5 normally broken categories when I instead load DSR.

**Comment by YuiKitamura** [comment]
Is this something that can be fixed?

**Comment by Grimrukh** [comment]
Hey all, sorry for the delay.

I've finally figured out this bug -- the fact that it only happens in certain categories on PTDE was the detail I was missing, and I definitely get the same issue. The bug is an internal error because those param tables have new fields in DSR that don't exist in PTDE, but Soulstruct is still trying to look them up.

Will push a fix and new built EXE very soon!

**Comment by YuiKitamura** [comment]
Can confirm issue is fixed for me as well. Thanks so much, Grim!
